### ISSUE TITLE
Enable syntax highlighting for code snippets

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/veteran-facing-services-tools#263]
**Is your feature request related to a problem? Please describe.**
Code snippets on pages like https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-unit-test/ do not have any syntax highlighting, making them harder to read. 

**Describe the solution you'd like**
Enable syntax highlighting for Gatsby

**Additional context**
https://www.gatsbyjs.org/packages/gatsby-transformer-remark/

**Comment by U-DON** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team #9532](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9532) via [**ZenHub**](https://www.zenhub.com/)
