### ISSUE TITLE
E2E tests are disabled with Yeoman + test docs

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/veteran-facing-services-tools#265]
**Describe the bug**
Following docs for application creation & E2E testing does not result in E2E test being run locally.
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-application
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-end-to-end-test
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/test

**To Reproduce**
1. Create app with yeoman
1. manifest looks like:
    ```json
    {
      "appName": "Your App",
      "entryFile": "./app-entry.jsx",
      "entryName": "yourapp",
      "rootUrl": "/yourapp"
    }
    ```
1. `src/applications/your-app/tests/00.your-app.e2e.spec.js` contains
    ```js
    module.exports['@disabled'] =
      !manifest.production || __BUILDTYPE__ !== 'production';
    ```
    *note: this does exist in example snippet https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-end-to-end-test*
1. run `yarn build` and `yarn watch`
1. run E2E test: `yarn test:e2e src/applications/your-app/tests/00.your-app.e2e.spec.js`
1. Message shows: `00.your-app.e2e.spec module is disabled, skipping...`

**Expected behavior**

Following the docs should result in successfully running E2E test.

**Notes**
Some solutions are:
- Remove the snippet from the Yeoman E2E test 
- Run prod build command `NODE_ENV=production yarn build --buildtype vagovprod` from https://github.com/department-of-veterans-affairs/vets-website#more-commands
- Add `production: true` to `src/applications/your-app/manifest.json`

I wasn't sure though which of these is the intended approach?

**Comment by U-DON** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team #9531](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9531) via [**ZenHub**](https://www.zenhub.com/)
