### ISSUE TITLE
Remove mention of named `screen` import from React Testing Library

### ISSUE THREAD

**Issue by Cgfor3** [department-of-veterans-affairs/veteran-facing-services-tools#634]
# Details

During the previous iteration of updating the unit test best practices document, we included an example with a statement that imports the `screen` utility directly from react testing library (RTL). We have not properly configured our testing environment to allow for this import, so this will be misleading for developers and lead to errors.

# Acceptance Criteria
- [ ] Update unit test best practices document to show how to properly import/define the `screen` utility

**Comment by timwright12** [comment]
closed for https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/25714
